Add Weights and Biases reference
EthicalML/awesome-production-machine-learning pull request #174
Opened 2021-02-01 17:28 UTC by AyushExel

Weights & Biases helps companies turn deep learning research projects into deployed software by helping teams track their models, visualize model performance and easily automate training and improving models.

2021-02-01 19:18 UTC, axsaucedo commented
Nice one

2021-02-01 19:19 UTC, axsaucedo commented
Actually, their product seems to be primarily commercial, so it will need to be in the commercial section

2021-02-01 19:19 UTC, axsaucedo requested changes

2021-02-01 19:19 UTC, axsaucedo commented on README.md
> +* [Weights & Biases](https://wandb.ai/site) ![](https://img.shields.io/github/stars/wandb/client?style=social)- Machine learning experiment tracking, dataset versioning, hyperparameter search, visual
move to commercial section

2021-02-07 20:35 UTC, axsaucedo commented
@AyushExel will you be able to add the requestsed changes?

2021-02-08 13:22 UTC, AyushExel commented
@axsaucedo W&B is free for individual users and academics. So I don't think it should be kept under the commercial section. Are you sure about that?

2021-02-08 13:35 UTC, axsaucedo commented
@AyushExel yep, commercial tools in the commercial section

2021-02-08 13:41 UTC, AyushExel commented
Done

2021-02-08 13:42 UTC, axsaucedo commented
@AyushExel awesome - thanks!

2021-02-08 13:42 UTC, merged