Add transformer-deploy project
EthicalML/awesome-production-machine-learning pull request #234
Opened 2022-01-11 13:00 UTC by pommedeterresautee

2022-01-15 17:03 UTC, axsaucedo commented on README.md
> +* [Transformer-deploy](https://github.com/ELS-RD/transformer-deploy/) ![](https://img.shields.io/github/stars/ELS-RD/transformer-deploy.svg?style=social) - Transformer-deploy is an efficient, scalabl
The list is alphabetic - this would just need to be sorted accordingly

2022-01-15 17:04 UTC, axsaucedo requested changes
Thank you for the contribution - looks good, only thing needs to be alphabetical order

2022-01-15 22:19 UTC, pommedeterresautee commented
Tks for your review. It's fixed.

2022-01-20 20:11 UTC, merged

2022-01-20 20:11 UTC, axsaucedo commented
Nice one - thanks