Remove irrevalent tools
EthicalML/awesome-production-machine-learning pull request #284
Opened 2022-11-10 04:42 UTC by zhimin-z

This PR aims to remove irrelevant tools for the corresponding categories.

2022-11-10 08:01 UTC, axsaucedo requested changes
Thanks for the contribution, I added a few questions to understand why projects are being removed as these all seem to align with CONTRIBUTING.md requirements, particularly the metadata managment systems

2022-11-10 08:01 UTC, axsaucedo commented on README.md
> -* [Apache Marvin](https://github.com/apache/incubator-marvin) ![](https://img.shields.io/github/stars/apache/incubator-marvin.svg?style=social) is a platform for model deployment and versioning that
Why removing marvin? Seems may be slipping into not as widely maintained but it's not archived so given still backed by apache foundation would assume still active

2022-11-12 08:50 UTC, axsaucedo commented
@zhimin-z thanks for re-adding atlas - it seems the rest of the comments are not addressed, I'm not yet clear of the thinking to remove these tools, would you be able to provide more details?

2022-11-12 18:49 UTC, zhimin-z commented
> @zhimin-z thanks for re-adding atlas - it seems the rest of the comments are not addressed, I'm not yet clear of the thinking to remove these tools, would you be able to provide more details?

I left the details in my replies. Which removal makes you confused? @axsaucedo

2022-11-15 23:00 UTC, zhimin-z commented
> I am not sure if the comments were shared - perhaps you need to apply the review? I can't see any replies on the current comments

Hi, @axsaucedo Can you see my followup comments [here](https://github.com/EthicalML/awesome-production-machine-learning/pull/284/files/871fc2cfcce64cb97dc181cd656ae41891c90922)?

2022-11-16 20:18 UTC, axsaucedo commented
No there are no comments
![image](https://user-images.githubusercontent.com/1447507/202285420-754c3e0d-c2f8-495a-b775-82db664057d3.png)

I assume the review hasn't been posted

2022-11-16 21:10 UTC, zhimin-z commented
> No there are no comments ![image](https://user-images.githubusercontent.com/1447507/202285420-754c3e0d-c2f8-495a-b775-82db664057d3.png)
> 
> I assume the review hasn't been posted

OK, that is weird. I would paste my comments here directly.

To begin with, allow me to clarify the logic behind the awesome list for production machine learning. A tool shall be listed here due to its nature that it _helps with the production of the machine learning lifecycle_, **AND** it should also either claim to help with the machine learning lifecycle (i.e. written explicitly in their documentation: "This tool aims to help with machine learning .......") or be widely recognized as a helper tool to machine learning lifecycle by the practitioners' community (i.e. de facto standards in ML production).

For example, tools like Ubuntu, Docker, NumPy, etc. can contribute to the machine learning lifecycle, and they are amazing tools, but we shall not list them here since they are not designed or specifically used for the machine learning process.

Considering this belief, I suggest removing 1) Metacat, 2) Marquez, and 3) Apache Marvi from our list.

1. Metacat
If you check its specification in its repo (it has no documentation), Metacat aims to provide a data discovery service. However, this does not necessarily correlate with machine learning. Out of curiosity, I also Googled this tool and attempted to discover how this tool can be used in a typical machine-learning lifecycle. I failed to locate any related material online. Maybe this tool can provide help in the training data discovery process, but I think it might not a good choice to keep it on the list for now. If someday the tools have better integration into the machine learning pipeline, which is yet widely recognized in the ML community or explicitly documented in its tool readme, then we should certainly contain it in our list.

2. Marquez
Similarly, Markquez seems more likely integrated into a typical ML pipeline than Metacat after I got a head-on experience with this tool. However, it still fails to either document how it can help a typical ML process **or** be recognized by the ML community widely. Several Google searches gave me no results on how it relates directly to machine learning production. 

3. Apache Marvi
According to its official documentation, there seems to be no way to figure out what this tool is used for. And I also check recent update content and doubt if this tool is literally dead or unmaintained. If we are unsure if this tool can help with model versioning or data versioning, then, we should not keep it on the model/data versioning module. Also, the star number of its repository is exactly 100, failing to meet our inclusion standard for over 100 stars. 100 stars for 4 years as an Apache tool indicates it indeed drew far less attention than its peers if any.

To sum up, our list aims to serve as the best tool catalog for the ML community in the foreseeable future. Then we should keep our bar for tool inclusion specifically for machine learning production. If the tools are not specifically used/designed for the machine learning process, then we shall add to our lie. What do you think? @axsaucedo

2022-11-18 09:55 UTC, axsaucedo commented
I've seen git doing this with comments when they are staged (i.e. commented as "bulk review") - thansk for sharing them in text form.

I do like the explicit definition of: `It helps with the production of the machine learning lifecycle, AND it should also either claim to help with the machine learning lifecycle (i.e. written explicitly in their documentation: "This tool aims to help with machine learning .......") or be widely recognized as a helper tool to machine learning lifecycle by the practitioners' community (i.e. de facto standards in ML production).`

I am keen to add this to the CONTRIBUTING.md, so people make the case for tools when adding one.

In regards to the ones to be removed.

#### 1. metacat
I see what you mean, I actually gave a talk recently about [metadata and service discovery](https://www.youtube.com/watch?v=wzbj7LcQ2Ek) in MLOPs and how it's different to the DataOps world. I agree that these data discovery services are limited, and could certainly be used for ML training data. I would still be keen to keep some of these if they are actually used in some way in ML, particularly with training data. Looking at some of the key posts about metacat they do reference quite a lot the usage of [Jupyter notebooks](https://netflixtechblog.com/metacat-making-big-data-discoverable-and-meaningful-at-netflix-56fb36a53520) which would suggest that data science / data analyst practitioners would be actively using this. Given this is analogous to Atlas I would be more inclined to keep.

#### 2. Marquez 
For Marquez and generally ETL platforms its easier to argue their fit for MLOps, there are some usecases referencing marquez for MLOPS (e.g. https://www.slideshare.net/WillyLulciuc/marquez-an-open-source-metadata-service-for-ml-platforms) so I would be inclined to keep this one (also as it's part of the LF AI & Data Foundation, ensuring it has interoperability with such projects).

#### 3. Apache Marvin
Yes good points, let's remove.

2022-11-18 15:53 UTC, zhimin-z commented
changed! @axsaucedo

2022-11-18 18:53 UTC, axsaucedo approved these changes
Great - thank you for the contribution

2022-11-18 18:53 UTC, merged