add cleanlab to Labeling Tools section
EthicalML/awesome-production-machine-learning pull request #306
Opened 2023-01-08 09:04 UTC by jwmueller

cleanlab nicely complements any labeling tool and is very useful to assess data & label quality

2023-01-15 16:44 UTC, axsaucedo requested changes
Thank you for the contribution, only change is it has to go in alphabetical order

2023-01-15 16:44 UTC, axsaucedo commented on README.md
> +* [cleanlab](https://github.com/cleanlab/cleanlab) ![](https://img.shields.io/github/stars/cleanlab/cleanlab?style=social) - Python library for data-centric AI. Can automatically: find mislabeled dat
Needs to go in alphabetical order

2023-01-15 22:47 UTC, jwmueller commented on README.md
> +* [cleanlab](https://github.com/cleanlab/cleanlab) ![](https://img.shields.io/github/stars/cleanlab/cleanlab?style=social) - Python library for data-centric AI. Can automatically: find mislabeled dat
done!

2023-01-15 22:48 UTC, jwmueller commented
moved the new section to respect alphabetical order

2023-01-16 06:42 UTC, axsaucedo approved these changes
Thanks - lgtm

2023-01-16 06:42 UTC, merged