Add clearrl tool and industry strength rl module
EthicalML/awesome-production-machine-learning pull request #308
Opened 2023-01-14 02:21 UTC by zhimin-z

also adjust the space of table of modules for uniformity

2023-01-15 16:41 UTC, axsaucedo commented on README.md
> +| [🍕 Industry-strength RL](#industry-strength-rl) | [📊 Industry-strength Visualisation](#industrial-strength-visualisation) | [🔠 Industry-strength NLP](#industrial-strength-nlp) |
Let's rename to "Reinforcement Learning"

2023-01-15 16:41 UTC, axsaucedo requested changes
This section looks very interesting, previously there has been an "unwritten rule" that in order to add a section there should be at least 3-5 projects, as otherwise we can end up with too much granularity, I would be keen to add this RL section, but I would be keen to make sure we add a couple of more resources. One that comes to mind is the Ray RL library.

Another point I would have is to call the section "Reinforcement Learning" instead of "industrial-RL" - I believe that NLP is more commonly referred to through its acronym, and although RL is a common acronym it may be better explicitly. Let's find a few more to add and then we can merge.

2023-01-15 16:45 UTC, axsaucedo commented
I have updated CONTRIBUTING.md to reflect this https://github.com/EthicalML/awesome-production-machine-learning/blob/master/CONTRIBUTING.md

2023-01-24 23:13 UTC, zhimin-z commented
> I have updated CONTRIBUTING.md to reflect this https://github.com/EthicalML/awesome-production-machine-learning/blob/master/CONTRIBUTING.md

Now take a look :) It meets all!

2023-01-25 01:27 UTC, zhimin-z commented
> This section looks very interesting, previously there has been an "unwritten rule" that in order to add a section there should be at least 3-5 projects, as otherwise we can end up with too much granularity, I would be keen to add this RL section, but I would be keen to make sure we add a couple of more resources. One that comes to mind is the Ray RL library.
> 
> Another point I would have is to call the section "Reinforcement Learning" instead of "industrial-RL" - I believe that NLP is more commonly referred to through its acronym, and although RL is a common acronym it may be better explicitly. Let's find a few more to add and then we can merge.

I tweak a bit on the module title but keep it short for referential convenience. Is that fine?
![image](https://user-images.githubusercontent.com/8592144/214459687-81ddfdc7-8da1-44f9-a27e-d820bad884fe.png)

2023-01-29 17:55 UTC, axsaucedo commented
Yes I think most people would konw what RL is

2023-01-29 17:55 UTC, merged