add nlp tools
EthicalML/awesome-production-machine-learning pull request #404
Opened 2023-03-16 19:05 UTC by zhimin-z

add Guardrails

2023-03-18 17:26 UTC, axsaucedo commented on README.md
> -* [mljar-supervised](https://github.com/mljar/mljar-supervised) ![](https://img.shields.io/github/stars/mljar/mljar-supervised.svg?style=social) - An Automated Machine Learning (AutoML) python packag
Seems removed by mistake

2023-03-18 17:26 UTC, axsaucedo commented on README.md
> +* [Github's Semantic](https://github.com/github/semantic) ![](https://img.shields.io/github/stars/github/semantic.svg?style=social) - Guardrails is a Python package for specifying structure and type,
Seems error

2023-03-18 17:26 UTC, axsaucedo commented on README.md
> +* [Guardrails](https://github.com/ShreyaR/guardrails) ![](https://img.shields.io/github/stars/ShreyaR/guardrails.svg?style=social) - Github's text library for parsing, analyzing, and comparing source
Error here as well

2023-03-18 17:27 UTC, axsaucedo requested changes
Comments on a few errors

2023-03-24 23:15 UTC, zhimin-z commented on README.md
> +* [Github's Semantic](https://github.com/github/semantic) ![](https://img.shields.io/github/stars/github/semantic.svg?style=social) - Guardrails is a Python package for specifying structure and type,
Done! @axsaucedo

2023-03-25 12:46 UTC, merged