add Safetensors
EthicalML/awesome-production-machine-learning pull request #447
Opened 2023-10-17 19:57 UTC by zhimin-z

2023-11-12 15:21 UTC, axsaucedo requested changes

2023-11-12 15:21 UTC, axsaucedo commented on README.md
> +| [⚔ Adversarial Robustness](#adversarial-robustness) | [💾 Data Storage Optimization](#data-storage-optimization) | [📓 Data Science Notebook](#data-science-notebook) |
Using UK spelling

2023-11-12 15:31 UTC, axsaucedo requested changes
Added another comment - would also be worth extending the title so all the libraries added are shown in the release notes

2023-11-12 15:31 UTC, axsaucedo commented on README.md
> +* [SafePO-Baselines](https://github.com/PKU-MARL/Safe-Policy-Optimisation) ![](https://img.shields.io/github/stars/PKU-MARL/Safe-Policy-Optimisation.svg?style=social) - SafePO-Baselines is a benchmar
It seems this would break

2024-01-01 00:39 UTC, zhimin-z commented
Is it good to ship? @axsaucedo

2024-01-01 00:41 UTC, axsaucedo approved these changes
There are some changes that appear as edits strangely, but we're doing squash commit so it should be OK

2024-01-01 00:41 UTC, merged